"""initial migration

Revision ID: 1ebbe971f818
Revises: 
Create Date: 2026-03-24 22:58:16.946439

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ebbe971f818'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'lineitems', 'orders', ['order_id'], ['id'])
    op.create_foreign_key(None, 'lineitems', 'products', ['product_id'], ['id'])
    op.create_foreign_key(None, 'refresh_token', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'refresh_token', type_='foreignkey')
    op.drop_constraint(None, 'lineitems', type_='foreignkey')
    op.drop_constraint(None, 'lineitems', type_='foreignkey')
    # ### end Alembic commands ###
