"""fix title column in documents

Revision ID: 2b2e1a535097
Revises: 9e8e5782bcb5
Create Date: 2026-04-01 09:52:04.318348

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b2e1a535097'
down_revision: Union[str, Sequence[str], None] = '9e8e5782bcb5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('title', sa.String(), nullable=False))
    op.drop_column('documents', 'titel')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('titel', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('documents', 'title')
    # ### end Alembic commands ###
