"""add documents table with vector column

Revision ID: 9e8e5782bcb5
Revises: b55e5ed6a95d
Create Date: 2026-03-31 22:54:13.990975

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e8e5782bcb5'
down_revision: Union[str, Sequence[str], None] = 'b55e5ed6a95d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
