from fastapi import APIRouter, Depends, HTTPException, status,Query
from sqlalchemy.orm import Session,selectinload
from app.api import deps
from app.schema.user import UserCreate, UserRead
from app.model.user import User
from app.model.refresh_token import RefreshToken
from app.crud.crud_user import requier_admin
from app.core.security import hashing_password
from datetime import datetime,timezone


router = APIRouter()

@router.post("/", response_model=UserRead, status_code=status.HTTP_201_CREATED)
def register_user(
    *,
    db: Session = Depends(deps.get_db),
    user_in: UserCreate
):
    """
    Step 1: Create a User so we can test the Checkout logic.
    - Checks if the email is already taken.
    - Saves the user to the DB.
    - Returns the user with their auto-generated ID.
    """
    # 1. Check for existing user (Senior Tip: Always check unique constraints)
    existing_user = db.query(User).filter(User.email == user_in.email).first()
    if existing_user:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="A user with this email already exists."
        )

    # 2. Map Schema to Model
    # We provide a default balance of 1000.0 so you can test successful purchases
    hashed = hashing_password(password=user_in.password)
    db_user = User(
        name=user_in.name,
        email=user_in.email,
        phone_number=user_in.phone_number,
        password = hashed,
        role = user_in.role,
        balance=1000.0,  # Starting money for testing Day 3 logic
        is_active=True
    )

    # 3. Save to Database
    db.add(db_user)
    db.commit()
    db.refresh(db_user) # This retrieves the ID generated by the DB
    
    return db_user





@router.delete("/users/{user_id}")
def delete_user(
    user_id: int,
    db: Session = Depends(deps.get_db),
    current_user: User = Depends(requier_admin)
):
    user = db.query(User).filter(User.id == user_id).first()
    if not user:
        raise HTTPException(status_code=404, detail="User not found")
    db.query(RefreshToken).filter(RefreshToken.user_id == user_id).delete()
    user.is_deleted = True
    user.deleted_at = datetime.now(timezone.utc)
    db.commit()
    return {"message": "User deleted"}


@router.get("/users")
def selectinload_and_pagination_check(*,
                                      skip: int = Query(default = 0,ge = 0),
                                      limit: int = Query(default=0,ge = 1,le = 100),
                                      db: Session = Depends(deps.get_db)):
    
    users = db.query(User).filter(User.is_deleted == False).options(selectinload(User.orders)).offset(skip).limit(limit).all()
    Total_count = db.query(User).filter(User.is_deleted == False).count()

    return {
        "Total_user_count": Total_count,
        "Skip": skip,
        "Limit": limit,
        "has_more": (skip + limit)< Total_count,
        "data": users
    }
    


